pizzas/urls.py
from django.urls import path
from . import views

"""Определение схемы URL для проекта Pizzeria"""
app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Pizzas page
    path('pizzas/', views.pizzas, name='pizzas'),
    # Pizza info page
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

# Create your models here.


class Pizza(models.Model):
    """ Модель пиццы"""
    name = models.CharField(max_length=200)

    """Строковое отображение названий пиццы"""
    def __str__(self):
        return self.name


class Topping(models.Model):
    """Модель топингов для пиццы"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    """Строковое отображение названий топингов"""
    def __str__(self):
        return self.name

pizzas/views.py
from django.shortcuts import render
from .models import Pizza

# Create your views here.


def index(request):
    """Домашняя страница приложения Pizzeria"""
    return render(request, 'pizzas/index.html')


def pizzas(request):
    """Вывод списка пицц"""
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Вывод пиццы со всеми топингами"""
    pizza = Pizza.objects.get(id=pizza_id)
    entries = pizza.topping_set.order_by('name')
    context = {'pizza': pizza, 'entries': entries}
    return render(request, 'pizzas/pizza.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Главная страница</a> --
    <a href="{% url 'pizzas:pizzas' %}">Пицца</a>
</p>

{% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Привет! Это домашняя страница моей пиццерии!</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

    <p>Пицца: {{ pizza }}</p>

    <p>Топинги:</p>
    <ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.name }}</p>
            <p>{{ entry.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>Топинги для этой пицы отсутствуют</li>
    {% endfor %}
    </ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Пицца:</p>

    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
            </li>
        {% empty %}
            <li>Пиццу пока не завезли. Загляните пожалуйста позже.</li>
        {% endfor %}
    </ul>

{% endblock content %}